[versions]
activityKtx = "1.10.0"
agp = "8.8.0" # "8.5.0"
converterGsonVersion = "2.9.0"
converterKotlinxSerializationVersion = "2.11.0"
converterScalars = "2.11.0"
hiltAndroid = "2.56.1"
hiltNavigationCompose = "1.2.0"
kotlin = "2.0.0" # "2.1.0"
coreKtx = "1.15.0" # "1.10.1"
junit = "4.13.2"
junitVersion = "1.2.1" # "1.1.5"
espressoCore = "3.6.1" # "3.5.1"
appcompat = "1.7.0" # "1.6.1"
kotlinMetadataJvm = "2.1.10"
kotlinxSerializationJson = "1.8.1"
lifecycleViewmodelKtx = "2.8.7"
lifesycleViewmodelComposeVersion = "2.8.7"
material = "1.12.0" # "1.10.0"
activity = "1.10.0" # "1.8.0"
constraintlayout = "2.2.0" # "2.1.4"
lifecycleRuntimeKtx = "2.8.7" # "2.6.1"
activityCompose = "1.10.0" # "1.8.0"
composeBom = "2025.04.01" # "2024.01.00"
navigationCompose = "2.8.9"
navigationRuntimeKtx = "2.8.5"
okhttp = "4.11.0"
retrofit = "2.11.0"
retrofit2KotlinxSerializationConverter = "1.0.0"
symbolProcessingApi = "2.1.20-1.0.31"

[libraries]
activity-ktx = { module = "androidx.activity:activity-ktx" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-lifesycle-viewmodel-compose = { module = "androidx.lifesycle:lifesycle-viewmodel-compose", version.ref = "lifesycleViewmodelComposeVersion" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version = "2.6.1" }
androidx-room-ktx = { module = "androidx.room:room-ktx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version = "2.6.1" }
androidx-room-testing = { module = "androidx.room:room-testing", version = "2.6.1" }
converter-scalars = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "converterScalars" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroid" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hiltAndroid" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlin-metadata-jvm = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm", version.ref = "kotlinMetadataJvm" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-navigation-runtime-ktx = { group = "androidx.navigation", name = "navigation-runtime-ktx", version.ref = "navigationRuntimeKtx" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit2-converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
retrofit2-converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "converterKotlinxSerializationVersion" }
retrofit2-kotlinx-serialization-converter = { module = "com.jakewharton.retrofit:retrofit2-kotlinx-serialization-converter", version.ref = "retrofit2KotlinxSerializationConverter" }
symbol-processing-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "symbolProcessingApi" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
